- id: ktlint
  name: ktlint
  description: Runs ktlint
  entry: ./scripts/ktlint.sh
  language: script
  files: \.kt(s)?$
- id: detekt
  name: detekt
  description: Runs detekt
  entry: ./scripts/detekt.sh
  language: script
  files: \.kt(s)?$
